import random

JOKES = [
    "Teacher: Homework kyu nahi kiya? Student: Sir network problem tha 😅",
    "Doctor: Aapko rest chahiye. Patient: Par mobile? Doctor: Usko bhi 😆",
    "Friend: Tu gym jaata hai? Me: Haan... Instagram pe 💀",
    "Papa: Result kaisa tha? Me: Sirf number kam aaye, baaki sab sahi tha 😭",
    "Life itni kharab hai ki alarm bhi sympathy me 5 min extra deta hai 😴",
    "WiFi slow ho toh patience level NASA jaisa ho jata hai 🚀",
    "Me: Aaj se padhai start. Also me after 5 min: YouTube open 😭",
    "Crush: Tum alag ho. Me: Matlab reject ho gaya 😅",
    "Online class ka sabse bada benefit: Attendance + sleep combo 😴",
    "Teacher: Silence! Me: Internally screaming 😵",

    "Bhai: Tu itna thak kyu gaya? Me: Kuch nahi, sapne me kaam kar raha tha 😴",
    "Exam: Surprise! Me: Heart attack 💀",
    "Mobile battery: 100% → 1% in 10 min 😭",
    "Friend: Chal padhai karte hain. Me: Meme dekh ke motivation lete hain 😆",
    "Gym membership li, ab bas motivation missing hai 😂",
    "Zindagi ek game hai, aur main lagatar lag kar raha hoon 🎮",
    "Teacher: Tum future me kya banoge? Me: Offline 😅",
    "Maa: Phone chhodo! Me: Last reel… (never last) 😂",
    "Salary aate hi: Bye bye money 💸",
    "Sleep schedule: Totally destroyed 😭",

    "Alarm: Wake up! Me: Ignore 😴",
    "Friend: Tu serious kab hota hai? Me: Jab internet slow ho 😡",
    "Google: Did you mean? Me: Haan bhai wahi 😆",
    "Papa: Mobile kam use karo. Me: Notes dekh raha tha 😅",
    "Life update: Still confused 🤯",
    "Exam me question: Out of syllabus 😭",
    "Teacher: Easy hai. Students: Impossible 💀",
    "Me: Kal se diet. Also me: Pizza order 🍕",
    "Internet off: Life off 😵",
    "Mood: Depends on WiFi 📶",

    "Friend: Chal bahar chalte hain. Me: Battery low 😅",
    "Laptop: Updating… Me: Cancel karo yaar 😭",
    "Assignment: Pending forever 📚",
    "Motivation: 0% 😴",
    "Reality: Hard. Me: Sleep 😴",
    "Crush online: Heartbeat fast 💓",
    "Crush offline: Panic attack 😭",
    "Exam result: Unexpected shock 💀",
    "Friend: Tu genius hai. Me: Bas luck hai 😂",
    "Life hack: Sleep more 😆",

    "Study plan: Fail ❌",
    "Netflix: Success ✔️",
    "Teacher: Answer bolo. Me: Silence mode 🔕",
    "Phone gir gaya: Heart attack 😱",
    "Internet fast: Happiness 😄",
    "Homework: Forgotten 😅",
    "Maa: Kaam karo! Me: Busy hoon 😆",
    "Sleep vs Study: Sleep wins 🏆",
    "Brain: Not responding 😴",
    "Life: Loading... ⏳",

    "Friend: Tu badal gaya hai. Me: Update ho gaya hoon 😂",
    "Mood swings: Unlimited 🎢",
    "Time: Fast. Work: Slow 😅",
    "Goal: Sleep peacefully 😴",
    "Reality check: Hard 💀",
    "Mind: Overthinking 🤯",
    "Internet: Best friend 📶",
    "Phone: Addiction 😅",
    "Life: Complicated 😵",
    "Me: Lazy forever 😂",

    "Study: Later 😆",
    "Sleep: Now 😴",
    "Friend: Chill kar. Me: Already 😎",
    "Brain: Error 404 🤖",
    "Teacher: Focus karo! Me: Lost 😅",
    "Game: Restart 🔄",
    "Life: Retry 😭",
    "Mood: Random 🎲",
    "Plan: Cancel ❌",
    "Me: Confused 😵",

    "Goal: Success 🏆",
    "Effort: Low 😅",
    "Sleep: High 😴",
    "Internet: Life 📶",
    "Reality: Tough 💀",
    "Me: Surviving 😆",
    "Friend: Legend 😂",
    "Teacher: Angry 😡",
    "Student: Crying 😭",
    "Exam: Disaster 💥"
]

def get_random_joke():
    return random.choice(JOKES)